### Mean_Tau_Av_Int Extraction Script

### Author:       Leander Rohr, ZMBP Tübingen

### Purpose:      Determines the mean of all extracted tau_Av_Int [ns] values from the CSV files generated with Script 1.
###               Thresholds can be set to exclude certain lifetimes.
###               Calculates the Interaction Pixel (IPS) Threshold based on the calculated mean and a set FRET Efficiency. 


### License:      [GPL-3.0 license]

### Last Updated: [2024-12-05]


### Description:
###     - Place all .csv files that were generated by Script 1 and belong to the same group (usually Donor-only Samples) in a single folder.
###     - Set the path to the folder (see line 42)
###     - The script processes each .csv file and print accumulated statistical values at the end (Mean, StDev, Counts) as well as the IPS Treshold.
###     - Certain lifetimes can be excluded to avoid false positive or negative results. Set the numbers in Line 67 and 68.
###     - Set the FRET Efficiency that defines Interacting Pixels (IPS). Set the number in Line 91.
###     - If required, missing dependencies are installed automatically.




# Remove all objects in the workspace
rm(list = ls())

# Ensure that all needed packages are installed and loaded
ensure_packages <- function(pkgs) {
  for (pkg in pkgs) {
    if (!requireNamespace(pkg, quietly = TRUE)) {
      install.packages(pkg, dependencies = TRUE)
    }
    library(pkg, character.only = TRUE)
  }
}
ensure_packages ("dplyr")

# Set the working directory and path. This should be the folder where all your .csv files from Script 1 are stored. 
# Please note that R only accepts "/" as slash
path <- "INSERT/FILE/PATH/HERE"
setwd(path)

# List all CSV files in the directory
file_list <- list.files(path, pattern = "*.csv", full.names = TRUE)

# Initialize an empty data frame to accumulate data from all files
combined_data <- data.frame()

# Loop through each file to read and combine data
for (file in file_list) {
  # Read the CSV file with comma as decimal separator
  data <- read.csv(file, header = TRUE, dec = ",")
  
  # Convert character columns to numeric where possible, suppressing any warnings
  numeric_data <- data %>%
    mutate(across(where(is.character), ~ suppressWarnings(as.numeric(.x)))) %>%
    select(where(~ sum(!is.na(.x)) > 0))  # Retain columns with valid numeric values
  
  # Append numeric data to the combined data frame
  combined_data <- bind_rows(combined_data, numeric_data)
}

# Filter the data to retain only values between "lower_limit" and "upper_limit". In this example code, values below 1.5 and above 2.7 are excluded. 
# Adjust the values for your needs. 
lower_limit <- 1.5
upper_limit <- 2.7

filtered_data <- combined_data %>%
  summarise(across(everything(), ~ .x[.x >= lower_limit & .x <= upper_limit], .names = "filtered_{.col}"))

# Calculate statistics for the filtered data
statistics <- filtered_data %>%
  summarise(
    across(
      everything(),
      list(
        mean = ~ mean(.x, na.rm = TRUE),
        sd = ~ sd(.x, na.rm = TRUE),
        count = ~ sum(!is.na(.x))
      ),
      .names = "{.fn}_{.col}"
    )
  )


# Calculate Threshold for IPS based on the mean and a specific FRET Efficiency that defines IPS

# Please enter the FRET Efficiency that defines an interaction (e.g. 0.1 is equal to 10 % FRET Efficiency) 
fret_efficiency <- 0.1 

# Extract the mean value(s) from the statistics data frame
mean_values <- statistics %>% select(starts_with("mean")) %>% as.numeric()

# Calculate the threshold for IPS for each mean value
threshold_IPS <- mean_values * (1 - fret_efficiency)


# Print the statistics and threshold_IPS
# Please save the threshold_IPS, since you need it for Script 3.
print(statistics)
print(threshold_IPS)